spring:
  #  数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dgmzuqiu123
    url: jdbc:mysql://124.70.22.80:3306/xinwen?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

# mybatis plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: none


# 配置清单